// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: agent.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterHost_FullMethodName       = "/proto.AgentService/RegisterHost"
	AgentService_ReprotState_FullMethodName        = "/proto.AgentService/ReprotState"
	AgentService_RequestCmd_FullMethodName         = "/proto.AgentService/RequestCmd"
	AgentService_ReturnCmdResult_FullMethodName    = "/proto.AgentService/ReturnCmdResult"
	AgentService_ReportMonitorEvent_FullMethodName = "/proto.AgentService/ReportMonitorEvent"
	AgentService_ReportUrlEvent_FullMethodName     = "/proto.AgentService/ReportUrlEvent"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type AgentServiceClient interface {
	// 设备注册
	RegisterHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Feedback, error)
	// 上报状态
	ReprotState(ctx context.Context, in *State, opts ...grpc.CallOption) (*Feedback, error)
	// 请求命令
	RequestCmd(ctx context.Context, in *Host, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cmd], error)
	// 返回命令结果
	ReturnCmdResult(ctx context.Context, in *CmdResult, opts ...grpc.CallOption) (*Feedback, error)
	// 上报告警
	ReportMonitorEvent(ctx context.Context, in *MonitorEvent, opts ...grpc.CallOption) (*Feedback, error)
	// 上报url告警
	ReportUrlEvent(ctx context.Context, in *UrlAlertEvent, opts ...grpc.CallOption) (*Feedback, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterHost(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, AgentService_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReprotState(ctx context.Context, in *State, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, AgentService_ReprotState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RequestCmd(ctx context.Context, in *Host, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Cmd], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_RequestCmd_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Host, Cmd]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RequestCmdClient = grpc.ServerStreamingClient[Cmd]

func (c *agentServiceClient) ReturnCmdResult(ctx context.Context, in *CmdResult, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, AgentService_ReturnCmdResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportMonitorEvent(ctx context.Context, in *MonitorEvent, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, AgentService_ReportMonitorEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportUrlEvent(ctx context.Context, in *UrlAlertEvent, opts ...grpc.CallOption) (*Feedback, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Feedback)
	err := c.cc.Invoke(ctx, AgentService_ReportUrlEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// 定义服务
type AgentServiceServer interface {
	// 设备注册
	RegisterHost(context.Context, *Host) (*Feedback, error)
	// 上报状态
	ReprotState(context.Context, *State) (*Feedback, error)
	// 请求命令
	RequestCmd(*Host, grpc.ServerStreamingServer[Cmd]) error
	// 返回命令结果
	ReturnCmdResult(context.Context, *CmdResult) (*Feedback, error)
	// 上报告警
	ReportMonitorEvent(context.Context, *MonitorEvent) (*Feedback, error)
	// 上报url告警
	ReportUrlEvent(context.Context, *UrlAlertEvent) (*Feedback, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterHost(context.Context, *Host) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedAgentServiceServer) ReprotState(context.Context, *State) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReprotState not implemented")
}
func (UnimplementedAgentServiceServer) RequestCmd(*Host, grpc.ServerStreamingServer[Cmd]) error {
	return status.Errorf(codes.Unimplemented, "method RequestCmd not implemented")
}
func (UnimplementedAgentServiceServer) ReturnCmdResult(context.Context, *CmdResult) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnCmdResult not implemented")
}
func (UnimplementedAgentServiceServer) ReportMonitorEvent(context.Context, *MonitorEvent) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMonitorEvent not implemented")
}
func (UnimplementedAgentServiceServer) ReportUrlEvent(context.Context, *UrlAlertEvent) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportUrlEvent not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterHost(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReprotState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(State)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReprotState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReprotState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReprotState(ctx, req.(*State))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RequestCmd_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Host)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).RequestCmd(m, &grpc.GenericServerStream[Host, Cmd]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_RequestCmdServer = grpc.ServerStreamingServer[Cmd]

func _AgentService_ReturnCmdResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReturnCmdResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReturnCmdResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReturnCmdResult(ctx, req.(*CmdResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportMonitorEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportMonitorEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportMonitorEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportMonitorEvent(ctx, req.(*MonitorEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportUrlEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UrlAlertEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportUrlEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportUrlEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportUrlEvent(ctx, req.(*UrlAlertEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _AgentService_RegisterHost_Handler,
		},
		{
			MethodName: "ReprotState",
			Handler:    _AgentService_ReprotState_Handler,
		},
		{
			MethodName: "ReturnCmdResult",
			Handler:    _AgentService_ReturnCmdResult_Handler,
		},
		{
			MethodName: "ReportMonitorEvent",
			Handler:    _AgentService_ReportMonitorEvent_Handler,
		},
		{
			MethodName: "ReportUrlEvent",
			Handler:    _AgentService_ReportUrlEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestCmd",
			Handler:       _AgentService_RequestCmd_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
