[server]
# 启动模式：debug/release
mode =  
# 公网IP
public_ip = 127.0.0.1
# 公网端口
public_port = 9090
# 本地IP
local_port = 9091

# 是否开启https
https = false

# 密钥模式：
# 1：使用配置文件的api-key进行校验
# 2：使用数据库的api-key进行校验
key_mode = 2

# api调用key
api-key = Xiaocheng
# 是否开启白名单模式
whitelist_mode = false

# 是否为触发接口开启认证
# 开启后需要在请求头中添加Authorization
# 建议在使用CDN的时候才开启
trigger_auth = false
trigger_auth_key = 4m-2024

[alert]
mode = 0
admin_email = 
