# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05proto\"<\n\x04Host\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\n\n\x02os\x18\x04 \x01(\t\"k\n\x05State\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x01\x12\x0e\n\x06memory\x18\x02 \x01(\x01\x12\x0c\n\x04\x64isk\x18\x03 \x01(\x01\x12\x0f\n\x07network\x18\x04 \x01(\x01\x12\n\n\x02io\x18\x05 \x01(\x01\x12\x0c\n\x04load\x18\x06 \x01(\x01\x12\x0c\n\x04time\x18\x07 \x01(\x03\"-\n\x03\x43md\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"V\n\tCmdResult\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\x02\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x12\n\nsuccessful\x18\x05 \x01(\x08\"/\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"n\n\x0cMonitorEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\teventType\x18\x02 \x01(\x04\x12\x11\n\ttimeStamp\x18\x03 \x01(\x04\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\x12\x10\n\x08jsonData\x18\x06 \x01(\t\"`\n\rUrlAlertEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimeStamp\x18\x02 \x01(\x04\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x13\n\x0b\x66ingerprint\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\t2\xbe\x02\n\x0c\x41gentService\x12,\n\x0cRegisterHost\x12\x0b.proto.Host\x1a\x0f.proto.Feedback\x12,\n\x0bReprotState\x12\x0c.proto.State\x1a\x0f.proto.Feedback\x12\'\n\nRequestCmd\x12\x0b.proto.Host\x1a\n.proto.Cmd0\x01\x12\x34\n\x0fReturnCmdResult\x12\x10.proto.CmdResult\x1a\x0f.proto.Feedback\x12:\n\x12ReportMonitorEvent\x12\x13.proto.MonitorEvent\x1a\x0f.proto.Feedback\x12\x37\n\x0eReportUrlEvent\x12\x14.proto.UrlAlertEvent\x1a\x0f.proto.FeedbackB\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_HOST']._serialized_start=22
  _globals['_HOST']._serialized_end=82
  _globals['_STATE']._serialized_start=84
  _globals['_STATE']._serialized_end=191
  _globals['_CMD']._serialized_start=193
  _globals['_CMD']._serialized_end=238
  _globals['_CMDRESULT']._serialized_start=240
  _globals['_CMDRESULT']._serialized_end=326
  _globals['_FEEDBACK']._serialized_start=328
  _globals['_FEEDBACK']._serialized_end=375
  _globals['_REPORT']._serialized_start=377
  _globals['_REPORT']._serialized_end=425
  _globals['_MONITOREVENT']._serialized_start=427
  _globals['_MONITOREVENT']._serialized_end=537
  _globals['_URLALERTEVENT']._serialized_start=539
  _globals['_URLALERTEVENT']._serialized_end=635
  _globals['_AGENTSERVICE']._serialized_start=638
  _globals['_AGENTSERVICE']._serialized_end=956
# @@protoc_insertion_point(module_scope)
