# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_server.proto.agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterHost = channel.unary_unary(
                '/proto.AgentService/RegisterHost',
                request_serializer=agent__pb2.Host.SerializeToString,
                response_deserializer=agent__pb2.Feedback.FromString,
                _registered_method=True)
        self.ReprotState = channel.unary_unary(
                '/proto.AgentService/ReprotState',
                request_serializer=agent__pb2.State.SerializeToString,
                response_deserializer=agent__pb2.Feedback.FromString,
                _registered_method=True)
        self.RequestCmd = channel.unary_stream(
                '/proto.AgentService/RequestCmd',
                request_serializer=agent__pb2.Host.SerializeToString,
                response_deserializer=agent__pb2.Cmd.FromString,
                _registered_method=True)
        self.ReturnCmdResult = channel.unary_unary(
                '/proto.AgentService/ReturnCmdResult',
                request_serializer=agent__pb2.CmdResult.SerializeToString,
                response_deserializer=agent__pb2.Feedback.FromString,
                _registered_method=True)
        self.ReportMonitorEvent = channel.unary_unary(
                '/proto.AgentService/ReportMonitorEvent',
                request_serializer=agent__pb2.MonitorEvent.SerializeToString,
                response_deserializer=agent__pb2.Feedback.FromString,
                _registered_method=True)
        self.ReportUrlEvent = channel.unary_unary(
                '/proto.AgentService/ReportUrlEvent',
                request_serializer=agent__pb2.UrlAlertEvent.SerializeToString,
                response_deserializer=agent__pb2.Feedback.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """定义服务
    """

    def RegisterHost(self, request, context):
        """设备注册
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReprotState(self, request, context):
        """上报状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCmd(self, request, context):
        """请求命令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnCmdResult(self, request, context):
        """返回命令结果
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMonitorEvent(self, request, context):
        """上报告警
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUrlEvent(self, request, context):
        """上报url告警
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterHost': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHost,
                    request_deserializer=agent__pb2.Host.FromString,
                    response_serializer=agent__pb2.Feedback.SerializeToString,
            ),
            'ReprotState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReprotState,
                    request_deserializer=agent__pb2.State.FromString,
                    response_serializer=agent__pb2.Feedback.SerializeToString,
            ),
            'RequestCmd': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestCmd,
                    request_deserializer=agent__pb2.Host.FromString,
                    response_serializer=agent__pb2.Cmd.SerializeToString,
            ),
            'ReturnCmdResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnCmdResult,
                    request_deserializer=agent__pb2.CmdResult.FromString,
                    response_serializer=agent__pb2.Feedback.SerializeToString,
            ),
            'ReportMonitorEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMonitorEvent,
                    request_deserializer=agent__pb2.MonitorEvent.FromString,
                    response_serializer=agent__pb2.Feedback.SerializeToString,
            ),
            'ReportUrlEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUrlEvent,
                    request_deserializer=agent__pb2.UrlAlertEvent.FromString,
                    response_serializer=agent__pb2.Feedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """定义服务
    """

    @staticmethod
    def RegisterHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AgentService/RegisterHost',
            agent__pb2.Host.SerializeToString,
            agent__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReprotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AgentService/ReprotState',
            agent__pb2.State.SerializeToString,
            agent__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCmd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.AgentService/RequestCmd',
            agent__pb2.Host.SerializeToString,
            agent__pb2.Cmd.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnCmdResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AgentService/ReturnCmdResult',
            agent__pb2.CmdResult.SerializeToString,
            agent__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMonitorEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AgentService/ReportMonitorEvent',
            agent__pb2.MonitorEvent.SerializeToString,
            agent__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUrlEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.AgentService/ReportUrlEvent',
            agent__pb2.UrlAlertEvent.SerializeToString,
            agent__pb2.Feedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
